language: generic

dist: "trusty"

env:
  matrix:
    - PYVER=2 VIMFLAV=vim
    - PYVER=3 VIMFLAV=vim
    - PYVER=2 VIMFLAV=nvim
    - PYVER=3 VIMFLAV=nvim

sudo: false

addons:
  apt:
    packages:
      - language-pack-ja
      # - vim
      # - libperl-dev
      - python-dev
      - python3-dev
      # - liblua5.1-0-dev
      # - lua5.1
      - realpath
      - python3-pip

cache:
  directories:
    - /tmp/vim
    - /tmp/vim-themis

install:
  - |
    case x"${VIMFLAV}" in
    xvim)
      if [ -d /tmp/vim/.git ]; then
        cd /tmp/vim
        git fetch
        if git diff --exit-code --quiet ..origin/master; then
          :
        else
          git reset --hard origin/master
          git clean -dfx
        fi
      else
        git clone --depth 1 --single-branch https://github.com/vim/vim /tmp/vim
        cd /tmp/vim
      fi
      case py"${PYVER}" in
      py2)
        PYTHONINTERP=--enable-pythoninterp
        ;;
      py3)
        PYTHONINTERP=--enable-python3interp
        ;;
      esac
      ./configure --prefix="$PWD/build" --with-features=huge $PYTHONINTERP --enable-fail-if-missing
      make -j2
      make install
      export PATH=$PWD/build/bin:$PATH
      cd "${TRAVIS_BUILD_DIR}"
      ;;
    xnvim)
      eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"
      case py"${PYVER}" in
        py2)
          pip2 install --user neovim
          ;;
        py3)
          pip3 install --user neovim
          ;;
      esac
      ;;
    esac
    if [ -d /tmp/vim-themis/.git ]; then
      git -C /tmp/vim-themis fetch
      git -C /tmp/vim-themis reset --hard origin/master
      git -C /tmp/vim-themis clean -dfx
    else
      git clone https://github.com/thinca/vim-themis --quiet --branch v1.5.3 --single-branch --depth 1 /tmp/vim-themis
    fi

script:
  - |
    case x"${VIMFLAV}" in
    xvim)
      vim --version
      ;;
    xnvim)
      nvim --version
      export THEMIS_VIM='nvim'
      export THEMIS_ARGS='-e --headless'
      ;;
    esac
    /tmp/vim-themis/bin/themis --reporter dot
